### ISSUE TITLE
Configure TopicSubscription with properties

### ISSUE THREAD

**Issue by tobiasschaefer** [NovatecConsulting/micronaut-camunda-external-client#9]
Currently, the topic subscription can only be configured with annotation properties

```java
@ExternalTaskSubscription(
    topicName = "test-topic",
    lockDuration = 19000,
    variables = ["test-one", "test-two"],
    localVariables = true
)
```

Let's also make these available via properties, i.e.

```yml
camunda.external-client:
  subscriptions:
    my-topic:
      lock-duration: 19000
      variables:
        - test-one
        - test-two
      local-variables: true
```

Note: Camel-Case and Kebab-Case should both be supported.
